/**
 * Static fixtures for the hrv-balance-tile DX comparison route.
 *
 * Hand-authored, wire-shaped `RecoveryView`s — NOT live data and never fetched.
 * The per-day band fields (`baselineAvg` / `balancedLow` / `balancedHigh` /
 * `zScore` / `status`) and `baselineTrend` are the server figures the rolling
 * baseline pass emits; variants display them as received and never recompute a
 * baseline in the browser.
 *
 * The numbers were solved offline against the same rolling rule the engine uses
 * — for each charted day, the mean and SD of the trailing 30 days ENDING THE DAY
 * BEFORE, requiring 14 samples — so the band genuinely drifts by the amount each
 * fixture claims rather than being eyeballed. Two invariants the API SOW puts
 * under test hold here too: `days[last]` agrees with the scalar `hrv` block on
 * status and both bounds, and `baselineTrend` is derived only from baselines,
 * never from `shortAvg` (in `falling` the two deliberately disagree).
 *
 * Throwaway — this file is never promoted to production.
 */

import type { RecoveryView } from "@/lib/dashboard";

export type FixtureKey =
  | "rising"
  | "falling"
  | "suppressed"
  | "partial-band"
  | "calibrating"
  | "no-reading-yet";

export type Fixture = {
  label: string;
  /** What this state is for, and what to look at. Shown under the switcher. */
  blurb: string;
  view: RecoveryView;
};

/** Switcher order — the six states every variant has to survive. */
export const FIXTURE_ORDER: FixtureKey[] = [
  "rising",
  "falling",
  "suppressed",
  "partial-band",
  "calibrating",
  "no-reading-yet",
];

export const FIXTURES: Record<FixtureKey, Fixture> = {
  rising: {
    label: "Rising",
    blurb:
      "The headline case, and the one the shipped tile cannot express: an ordinary 77 ms morning sitting half an SD below an 88 ms baseline — comfortably inside the 68–108 band — while the baseline itself has climbed 6 ms over four weeks, from 82. Two interior nights are missing. Can you SEE the climb, or do you have to read a tag?",
    view: {
      restingToday: 58,
      recoveryScore: 70,
      hrvToday: 77.4,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: 59,
          recoveryScore: 79,
          hrv: 100.2,
          baselineAvg: 79.9,
          balancedLow: 59.5,
          balancedHigh: 100.2,
          zScore: 1,
          status: "balanced",
        },
        {
          date: "2026-07-11",
          restingHr: 59,
          recoveryScore: 68,
          hrv: 80.1,
          baselineAvg: 81.5,
          balancedLow: 61.4,
          balancedHigh: 101.5,
          zScore: -0.07,
          status: "balanced",
        },
        {
          date: "2026-07-12",
          restingHr: 57,
          recoveryScore: 60,
          hrv: 72.2,
          baselineAvg: 81.8,
          balancedLow: 61.8,
          balancedHigh: 101.8,
          zScore: -0.48,
          status: "balanced",
        },
        {
          date: "2026-07-13",
          restingHr: 57,
          recoveryScore: 76,
          hrv: 96.7,
          baselineAvg: 81.1,
          balancedLow: 61.2,
          balancedHigh: 101.1,
          zScore: 0.78,
          status: "balanced",
        },
        {
          date: "2026-07-14",
          restingHr: 59,
          recoveryScore: 60,
          hrv: 73,
          baselineAvg: 81.6,
          balancedLow: 61.4,
          balancedHigh: 101.7,
          zScore: -0.42,
          status: "balanced",
        },
        {
          date: "2026-07-15",
          restingHr: 55,
          recoveryScore: 66,
          hrv: 93,
          baselineAvg: 81.5,
          balancedLow: 61.3,
          balancedHigh: 101.6,
          zScore: 0.57,
          status: "balanced",
        },
        {
          date: "2026-07-16",
          restingHr: 59,
          recoveryScore: 69,
          hrv: 79.8,
          baselineAvg: 83.4,
          balancedLow: 64.8,
          balancedHigh: 101.9,
          zScore: -0.19,
          status: "balanced",
        },
        {
          date: "2026-07-17",
          restingHr: 56,
          recoveryScore: 64,
          hrv: 63.2,
          baselineAvg: 83.3,
          balancedLow: 64.8,
          balancedHigh: 101.9,
          zScore: -1.09,
          status: "suppressed",
        },
        {
          date: "2026-07-18",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 81.8,
          balancedLow: 63.5,
          balancedHigh: 100.2,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-19",
          restingHr: 59,
          recoveryScore: 65,
          hrv: 70,
          baselineAvg: 82.9,
          balancedLow: 65.2,
          balancedHigh: 100.6,
          zScore: -0.73,
          status: "balanced",
        },
        {
          date: "2026-07-20",
          restingHr: 55,
          recoveryScore: 80,
          hrv: 89.5,
          baselineAvg: 82.2,
          balancedLow: 64.4,
          balancedHigh: 100,
          zScore: 0.41,
          status: "balanced",
        },
        {
          date: "2026-07-21",
          restingHr: 59,
          recoveryScore: 63,
          hrv: 74.1,
          baselineAvg: 83.8,
          balancedLow: 67.6,
          balancedHigh: 100,
          zScore: -0.6,
          status: "balanced",
        },
        {
          date: "2026-07-22",
          restingHr: 58,
          recoveryScore: 64,
          hrv: 75.2,
          baselineAvg: 83.6,
          balancedLow: 67.3,
          balancedHigh: 99.9,
          zScore: -0.51,
          status: "balanced",
        },
        {
          date: "2026-07-23",
          restingHr: 58,
          recoveryScore: 76,
          hrv: 144.7,
          baselineAvg: 83.3,
          balancedLow: 67.2,
          balancedHigh: 99.4,
          zScore: 3.82,
          status: "elevated",
        },
        {
          date: "2026-07-24",
          restingHr: 59,
          recoveryScore: 62,
          hrv: 100.1,
          baselineAvg: 84.4,
          balancedLow: 65.5,
          balancedHigh: 103.2,
          zScore: 0.84,
          status: "balanced",
        },
        {
          date: "2026-07-25",
          restingHr: 58,
          recoveryScore: 67,
          hrv: 120.9,
          baselineAvg: 85.7,
          balancedLow: 67.1,
          balancedHigh: 104.2,
          zScore: 1.9,
          status: "elevated",
        },
        {
          date: "2026-07-26",
          restingHr: 55,
          recoveryScore: 78,
          hrv: 106.4,
          baselineAvg: 87.2,
          balancedLow: 67.6,
          balancedHigh: 106.8,
          zScore: 0.98,
          status: "balanced",
        },
        {
          date: "2026-07-27",
          restingHr: 57,
          recoveryScore: 79,
          hrv: 55.3,
          baselineAvg: 87.8,
          balancedLow: 68,
          balancedHigh: 107.7,
          zScore: -1.64,
          status: "suppressed",
        },
        {
          date: "2026-07-28",
          restingHr: 55,
          recoveryScore: 72,
          hrv: 86.5,
          baselineAvg: 87.4,
          balancedLow: 66.9,
          balancedHigh: 107.8,
          zScore: -0.04,
          status: "balanced",
        },
        {
          date: "2026-07-29",
          restingHr: 57,
          recoveryScore: 72,
          hrv: 72.9,
          baselineAvg: 87.1,
          balancedLow: 66.7,
          balancedHigh: 107.6,
          zScore: -0.7,
          status: "balanced",
        },
        {
          date: "2026-07-30",
          restingHr: 59,
          recoveryScore: 67,
          hrv: 76.1,
          baselineAvg: 87.1,
          balancedLow: 66.6,
          balancedHigh: 107.5,
          zScore: -0.54,
          status: "balanced",
        },
        {
          date: "2026-07-31",
          restingHr: 57,
          recoveryScore: 80,
          hrv: 96.2,
          baselineAvg: 86.1,
          balancedLow: 65.8,
          balancedHigh: 106.5,
          zScore: 0.49,
          status: "balanced",
        },
        {
          date: "2026-08-01",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 87,
          balancedLow: 66.9,
          balancedHigh: 107.2,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-02",
          restingHr: 59,
          recoveryScore: 76,
          hrv: 126.4,
          baselineAvg: 85.6,
          balancedLow: 66.6,
          balancedHigh: 104.7,
          zScore: 2.14,
          status: "elevated",
        },
        {
          date: "2026-08-03",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 93.5,
          baselineAvg: 87.3,
          balancedLow: 66.8,
          balancedHigh: 107.7,
          zScore: 0.3,
          status: "balanced",
        },
        {
          date: "2026-08-04",
          restingHr: 56,
          recoveryScore: 79,
          hrv: 66.4,
          baselineAvg: 88.8,
          balancedLow: 69.5,
          balancedHigh: 108.1,
          zScore: -1.16,
          status: "suppressed",
        },
        {
          date: "2026-08-05",
          restingHr: 57,
          recoveryScore: 62,
          hrv: 102,
          baselineAvg: 88.1,
          balancedLow: 68.3,
          balancedHigh: 107.8,
          zScore: 0.71,
          status: "balanced",
        },
        {
          date: "2026-08-06",
          restingHr: 58,
          recoveryScore: 71,
          hrv: 86,
          baselineAvg: 88.4,
          balancedLow: 68.5,
          balancedHigh: 108.3,
          zScore: -0.12,
          status: "balanced",
        },
        {
          date: "2026-08-07",
          restingHr: 58,
          recoveryScore: 78,
          hrv: 66.1,
          baselineAvg: 88,
          balancedLow: 68.2,
          balancedHigh: 107.8,
          zScore: -1.11,
          status: "suppressed",
        },
        {
          date: "2026-08-08",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 103.1,
          baselineAvg: 87,
          balancedLow: 66.8,
          balancedHigh: 107.2,
          zScore: 0.8,
          status: "balanced",
        },
        {
          date: "2026-08-09",
          restingHr: 58,
          recoveryScore: 70,
          hrv: 77.4,
          baselineAvg: 88.2,
          balancedLow: 68.1,
          balancedHigh: 108.3,
          zScore: -0.54,
          status: "balanced",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: 57.2,
        restingHrDays: 28,
        hrvAvg: 88.2,
        hrvStdDev: 20.1,
        hrvDays: 30,
        recoveryScoreAvg: 70.4,
        recoveryScoreDays: 28,
      },
      hrv: {
        status: "balanced",
        balancedLow: 68.1,
        balancedHigh: 108.3,
        zScore: -0.54,
        trend: "steady",
        shortAvg: 84.9,
      },
      baselineTrend: {
        direction: "rising",
        deltaMs: 6.4,
        fromAvg: 81.8,
        overDays: 28,
      },
    },
  },
  falling: {
    label: "Falling",
    blurb:
      "The mirror case, and the one with product weight. Today's 79 ms reads Balanced against a band that has quietly sunk 8 ms in four weeks, 94 → 86. hrv.trend still says steady — the two questions are allowed to disagree. A variant that renders this almost identically to `rising` has solved the visual brief and missed the product one.",
    view: {
      restingToday: 59,
      recoveryScore: 63,
      hrvToday: 79,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: 60,
          recoveryScore: 54,
          hrv: 99.7,
          baselineAvg: 93.9,
          balancedLow: 76,
          balancedHigh: 111.9,
          zScore: 0.32,
          status: "balanced",
        },
        {
          date: "2026-07-11",
          restingHr: 61,
          recoveryScore: 73,
          hrv: 76.1,
          baselineAvg: 94.2,
          balancedLow: 76.3,
          balancedHigh: 112.2,
          zScore: -1.01,
          status: "suppressed",
        },
        {
          date: "2026-07-12",
          restingHr: 61,
          recoveryScore: 53,
          hrv: 109,
          baselineAvg: 94.3,
          balancedLow: 76.4,
          balancedHigh: 112.2,
          zScore: 0.82,
          status: "balanced",
        },
        {
          date: "2026-07-13",
          restingHr: 58,
          recoveryScore: 55,
          hrv: 117.9,
          baselineAvg: 94.8,
          balancedLow: 76.7,
          balancedHigh: 112.9,
          zScore: 1.28,
          status: "elevated",
        },
        {
          date: "2026-07-14",
          restingHr: 60,
          recoveryScore: 69,
          hrv: 75.6,
          baselineAvg: 95.9,
          balancedLow: 77.4,
          balancedHigh: 114.4,
          zScore: -1.1,
          status: "suppressed",
        },
        {
          date: "2026-07-15",
          restingHr: 61,
          recoveryScore: 57,
          hrv: 89.9,
          baselineAvg: 94.7,
          balancedLow: 76.1,
          balancedHigh: 113.3,
          zScore: -0.26,
          status: "balanced",
        },
        {
          date: "2026-07-16",
          restingHr: 60,
          recoveryScore: 74,
          hrv: 68.3,
          baselineAvg: 92.8,
          balancedLow: 76.7,
          balancedHigh: 109,
          zScore: -1.52,
          status: "suppressed",
        },
        {
          date: "2026-07-17",
          restingHr: 57,
          recoveryScore: 74,
          hrv: 80.2,
          baselineAvg: 92.6,
          balancedLow: 76.1,
          balancedHigh: 109.1,
          zScore: -0.75,
          status: "balanced",
        },
        {
          date: "2026-07-18",
          restingHr: 61,
          recoveryScore: 51,
          hrv: 105.6,
          baselineAvg: 91.7,
          balancedLow: 75.2,
          balancedHigh: 108.2,
          zScore: 0.84,
          status: "balanced",
        },
        {
          date: "2026-07-19",
          restingHr: 59,
          recoveryScore: 61,
          hrv: 101.1,
          baselineAvg: 93.1,
          balancedLow: 77.1,
          balancedHigh: 109.1,
          zScore: 0.5,
          status: "balanced",
        },
        {
          date: "2026-07-20",
          restingHr: 61,
          recoveryScore: 64,
          hrv: 91.3,
          baselineAvg: 93.4,
          balancedLow: 77.4,
          balancedHigh: 109.5,
          zScore: -0.13,
          status: "balanced",
        },
        {
          date: "2026-07-21",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 93.7,
          balancedLow: 77.7,
          balancedHigh: 109.6,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-22",
          restingHr: 57,
          recoveryScore: 72,
          hrv: 105.9,
          baselineAvg: 94.1,
          balancedLow: 77.9,
          balancedHigh: 110.2,
          zScore: 0.73,
          status: "balanced",
        },
        {
          date: "2026-07-23",
          restingHr: 60,
          recoveryScore: 65,
          hrv: 92.8,
          baselineAvg: 95,
          balancedLow: 78.9,
          balancedHigh: 111,
          zScore: -0.13,
          status: "balanced",
        },
        {
          date: "2026-07-24",
          restingHr: 61,
          recoveryScore: 61,
          hrv: 84.6,
          baselineAvg: 94.6,
          balancedLow: 78.6,
          balancedHigh: 110.6,
          zScore: -0.63,
          status: "balanced",
        },
        {
          date: "2026-07-25",
          restingHr: 61,
          recoveryScore: 55,
          hrv: 98.7,
          baselineAvg: 94.8,
          balancedLow: 79,
          balancedHigh: 110.6,
          zScore: 0.25,
          status: "balanced",
        },
        {
          date: "2026-07-26",
          restingHr: 60,
          recoveryScore: 77,
          hrv: 93.6,
          baselineAvg: 94.8,
          balancedLow: 79,
          balancedHigh: 110.6,
          zScore: -0.07,
          status: "balanced",
        },
        {
          date: "2026-07-27",
          restingHr: 61,
          recoveryScore: 65,
          hrv: 64.4,
          baselineAvg: 95.2,
          balancedLow: 79.7,
          balancedHigh: 110.8,
          zScore: -1.98,
          status: "suppressed",
        },
        {
          date: "2026-07-28",
          restingHr: 60,
          recoveryScore: 57,
          hrv: 74.9,
          baselineAvg: 94.2,
          balancedLow: 77.9,
          balancedHigh: 110.5,
          zScore: -1.18,
          status: "suppressed",
        },
        {
          date: "2026-07-29",
          restingHr: 59,
          recoveryScore: 65,
          hrv: 32.1,
          baselineAvg: 93.1,
          balancedLow: 76.6,
          balancedHigh: 109.6,
          zScore: -3.69,
          status: "suppressed",
        },
        {
          date: "2026-07-30",
          restingHr: 57,
          recoveryScore: 66,
          hrv: 110.7,
          baselineAvg: 91.8,
          balancedLow: 72.2,
          balancedHigh: 111.3,
          zScore: 0.97,
          status: "balanced",
        },
        {
          date: "2026-07-31",
          restingHr: 58,
          recoveryScore: 72,
          hrv: 49.7,
          baselineAvg: 92.6,
          balancedLow: 72.8,
          balancedHigh: 112.5,
          zScore: -2.16,
          status: "suppressed",
        },
        {
          date: "2026-08-01",
          restingHr: 60,
          recoveryScore: 65,
          hrv: 93.9,
          baselineAvg: 91.4,
          balancedLow: 70,
          balancedHigh: 112.7,
          zScore: 0.12,
          status: "balanced",
        },
        {
          date: "2026-08-02",
          restingHr: 61,
          recoveryScore: 64,
          hrv: 82,
          baselineAvg: 91.4,
          balancedLow: 70.1,
          balancedHigh: 112.7,
          zScore: -0.44,
          status: "balanced",
        },
        {
          date: "2026-08-03",
          restingHr: 60,
          recoveryScore: 62,
          hrv: 81.4,
          baselineAvg: 90.9,
          balancedLow: 69.6,
          balancedHigh: 112.3,
          zScore: -0.45,
          status: "balanced",
        },
        {
          date: "2026-08-04",
          restingHr: 61,
          recoveryScore: 66,
          hrv: 110.9,
          baselineAvg: 89.3,
          balancedLow: 69.1,
          balancedHigh: 109.6,
          zScore: 1.07,
          status: "elevated",
        },
        {
          date: "2026-08-05",
          restingHr: 58,
          recoveryScore: 65,
          hrv: 94.7,
          baselineAvg: 88.4,
          balancedLow: 69.8,
          balancedHigh: 107.1,
          zScore: 0.34,
          status: "balanced",
        },
        {
          date: "2026-08-06",
          restingHr: 58,
          recoveryScore: 67,
          hrv: 73,
          baselineAvg: 88.6,
          balancedLow: 69.9,
          balancedHigh: 107.2,
          zScore: -0.83,
          status: "balanced",
        },
        {
          date: "2026-08-07",
          restingHr: 61,
          recoveryScore: 61,
          hrv: 96.3,
          baselineAvg: 88.2,
          balancedLow: 69.3,
          balancedHigh: 107.1,
          zScore: 0.43,
          status: "balanced",
        },
        {
          date: "2026-08-08",
          restingHr: 60,
          recoveryScore: 68,
          hrv: 45.8,
          baselineAvg: 88.3,
          balancedLow: 69.4,
          balancedHigh: 107.2,
          zScore: -2.25,
          status: "suppressed",
        },
        {
          date: "2026-08-09",
          restingHr: 59,
          recoveryScore: 63,
          hrv: 79,
          baselineAvg: 86.2,
          balancedLow: 66.1,
          balancedHigh: 106.3,
          zScore: -0.36,
          status: "balanced",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: 59.2,
        restingHrDays: 28,
        hrvAvg: 86.2,
        hrvStdDev: 20.1,
        hrvDays: 30,
        recoveryScoreAvg: 64.4,
        recoveryScoreDays: 28,
      },
      hrv: {
        status: "balanced",
        balancedLow: 66.1,
        balancedHigh: 106.3,
        zScore: -0.36,
        trend: "steady",
        shortAvg: 83,
      },
      baselineTrend: {
        direction: "falling",
        deltaMs: -8.1,
        fromAvg: 94.3,
        overDays: 28,
      },
    },
  },
  suppressed: {
    label: "Suppressed",
    blurb:
      "The dramatic state: 61 ms at z −1.36, well under a steady band. It must read as true and slightly concerning — never as an alarm, and never in an imported traffic-light red.",
    view: {
      restingToday: 61,
      recoveryScore: 50,
      hrvToday: 61,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: 63,
          recoveryScore: 49,
          hrv: 71.6,
          baselineAvg: 84.8,
          balancedLow: 65.3,
          balancedHigh: 104.3,
          zScore: -0.68,
          status: "balanced",
        },
        {
          date: "2026-07-11",
          restingHr: 60,
          recoveryScore: 63,
          hrv: 110,
          baselineAvg: 85.5,
          balancedLow: 66.8,
          balancedHigh: 104.2,
          zScore: 1.31,
          status: "elevated",
        },
        {
          date: "2026-07-12",
          restingHr: 60,
          recoveryScore: 61,
          hrv: 97.8,
          baselineAvg: 87.2,
          balancedLow: 68.7,
          balancedHigh: 105.7,
          zScore: 0.57,
          status: "balanced",
        },
        {
          date: "2026-07-13",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 88.3,
          balancedLow: 70,
          balancedHigh: 106.5,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-14",
          restingHr: 61,
          recoveryScore: 70,
          hrv: 108.3,
          baselineAvg: 89.3,
          balancedLow: 71.6,
          balancedHigh: 106.9,
          zScore: 1.08,
          status: "elevated",
        },
        {
          date: "2026-07-15",
          restingHr: 63,
          recoveryScore: 59,
          hrv: 77.5,
          baselineAvg: 90.7,
          balancedLow: 73.2,
          balancedHigh: 108.2,
          zScore: -0.75,
          status: "balanced",
        },
        {
          date: "2026-07-16",
          restingHr: 63,
          recoveryScore: 64,
          hrv: 113.6,
          baselineAvg: 90.2,
          balancedLow: 72.6,
          balancedHigh: 107.9,
          zScore: 1.32,
          status: "elevated",
        },
        {
          date: "2026-07-17",
          restingHr: 60,
          recoveryScore: 49,
          hrv: 72.3,
          baselineAvg: 91.2,
          balancedLow: 73.1,
          balancedHigh: 109.4,
          zScore: -1.04,
          status: "suppressed",
        },
        {
          date: "2026-07-18",
          restingHr: 60,
          recoveryScore: 45,
          hrv: 92.4,
          baselineAvg: 90.4,
          balancedLow: 72,
          balancedHigh: 108.9,
          zScore: 0.11,
          status: "balanced",
        },
        {
          date: "2026-07-19",
          restingHr: 62,
          recoveryScore: 56,
          hrv: 82.6,
          baselineAvg: 90.8,
          balancedLow: 72.5,
          balancedHigh: 109.2,
          zScore: -0.45,
          status: "balanced",
        },
        {
          date: "2026-07-20",
          restingHr: 59,
          recoveryScore: 47,
          hrv: 73.2,
          baselineAvg: 90.3,
          balancedLow: 71.9,
          balancedHigh: 108.7,
          zScore: -0.93,
          status: "balanced",
        },
        {
          date: "2026-07-21",
          restingHr: 61,
          recoveryScore: 60,
          hrv: 80.7,
          baselineAvg: 89.6,
          balancedLow: 71,
          balancedHigh: 108.2,
          zScore: -0.48,
          status: "balanced",
        },
        {
          date: "2026-07-22",
          restingHr: 60,
          recoveryScore: 65,
          hrv: 101.8,
          baselineAvg: 89.8,
          balancedLow: 71.4,
          balancedHigh: 108.3,
          zScore: 0.65,
          status: "balanced",
        },
        {
          date: "2026-07-23",
          restingHr: 59,
          recoveryScore: 51,
          hrv: 106.2,
          baselineAvg: 90.4,
          balancedLow: 71.8,
          balancedHigh: 109,
          zScore: 0.85,
          status: "balanced",
        },
        {
          date: "2026-07-24",
          restingHr: 60,
          recoveryScore: 62,
          hrv: 108,
          baselineAvg: 90.5,
          balancedLow: 71.8,
          balancedHigh: 109.2,
          zScore: 0.93,
          status: "balanced",
        },
        {
          date: "2026-07-25",
          restingHr: 60,
          recoveryScore: 60,
          hrv: 78,
          baselineAvg: 91,
          balancedLow: 72.1,
          balancedHigh: 110,
          zScore: -0.69,
          status: "balanced",
        },
        {
          date: "2026-07-26",
          restingHr: 61,
          recoveryScore: 46,
          hrv: 102.7,
          baselineAvg: 90.7,
          balancedLow: 71.7,
          balancedHigh: 109.8,
          zScore: 0.63,
          status: "balanced",
        },
        {
          date: "2026-07-27",
          restingHr: 59,
          recoveryScore: 57,
          hrv: 116.8,
          baselineAvg: 92,
          balancedLow: 73.3,
          balancedHigh: 110.6,
          zScore: 1.33,
          status: "elevated",
        },
        {
          date: "2026-07-28",
          restingHr: 59,
          recoveryScore: 45,
          hrv: 49.2,
          baselineAvg: 92.6,
          balancedLow: 73.4,
          balancedHigh: 111.8,
          zScore: -2.26,
          status: "suppressed",
        },
        {
          date: "2026-07-29",
          restingHr: 63,
          recoveryScore: 67,
          hrv: 45.7,
          baselineAvg: 91.2,
          balancedLow: 70.4,
          balancedHigh: 111.9,
          zScore: -2.19,
          status: "suppressed",
        },
        {
          date: "2026-07-30",
          restingHr: 61,
          recoveryScore: 51,
          hrv: 111.2,
          baselineAvg: 89.4,
          balancedLow: 67.1,
          balancedHigh: 111.7,
          zScore: 0.98,
          status: "balanced",
        },
        {
          date: "2026-07-31",
          restingHr: 63,
          recoveryScore: 63,
          hrv: 110.1,
          baselineAvg: 90.8,
          balancedLow: 68.5,
          balancedHigh: 113.1,
          zScore: 0.86,
          status: "balanced",
        },
        {
          date: "2026-08-01",
          restingHr: 61,
          recoveryScore: 50,
          hrv: 81.2,
          baselineAvg: 90.9,
          balancedLow: 68.5,
          balancedHigh: 113.3,
          zScore: -0.43,
          status: "balanced",
        },
        {
          date: "2026-08-02",
          restingHr: 63,
          recoveryScore: 56,
          hrv: 69,
          baselineAvg: 90.7,
          balancedLow: 68.2,
          balancedHigh: 113.2,
          zScore: -0.97,
          status: "balanced",
        },
        {
          date: "2026-08-03",
          restingHr: 62,
          recoveryScore: 52,
          hrv: 84.6,
          baselineAvg: 90,
          balancedLow: 67.2,
          balancedHigh: 112.9,
          zScore: -0.24,
          status: "balanced",
        },
        {
          date: "2026-08-04",
          restingHr: 61,
          recoveryScore: 60,
          hrv: 79.8,
          baselineAvg: 90.4,
          balancedLow: 67.8,
          balancedHigh: 113.1,
          zScore: -0.47,
          status: "balanced",
        },
        {
          date: "2026-08-05",
          restingHr: 60,
          recoveryScore: 51,
          hrv: 85.2,
          baselineAvg: 89.4,
          balancedLow: 67,
          balancedHigh: 111.8,
          zScore: -0.19,
          status: "balanced",
        },
        {
          date: "2026-08-06",
          restingHr: 59,
          recoveryScore: 53,
          hrv: 59.9,
          baselineAvg: 90.1,
          balancedLow: 68.2,
          balancedHigh: 112,
          zScore: -1.38,
          status: "suppressed",
        },
        {
          date: "2026-08-07",
          restingHr: 61,
          recoveryScore: 69,
          hrv: 66.8,
          baselineAvg: 89.4,
          balancedLow: 66.9,
          balancedHigh: 111.9,
          zScore: -1,
          status: "balanced",
        },
        {
          date: "2026-08-08",
          restingHr: 63,
          recoveryScore: 52,
          hrv: 115.9,
          baselineAvg: 86.4,
          balancedLow: 67,
          balancedHigh: 105.9,
          zScore: 1.52,
          status: "elevated",
        },
        {
          date: "2026-08-09",
          restingHr: 61,
          recoveryScore: 50,
          hrv: 61,
          baselineAvg: 88,
          balancedLow: 68.1,
          balancedHigh: 107.9,
          zScore: -1.36,
          status: "suppressed",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: 61.2,
        restingHrDays: 28,
        hrvAvg: 88,
        hrvStdDev: 19.9,
        hrvDays: 30,
        recoveryScoreAvg: 58.4,
        recoveryScoreDays: 28,
      },
      hrv: {
        status: "suppressed",
        balancedLow: 68.1,
        balancedHigh: 107.9,
        zScore: -1.36,
        trend: "falling",
        shortAvg: 79,
      },
      baselineTrend: {
        direction: "steady",
        deltaMs: 0.8,
        fromAvg: 87.2,
        overDays: 28,
      },
    },
  },
  "partial-band": {
    label: "Partial band",
    blurb:
      "Forty nights of history, so the five oldest charted days have fewer than 14 readings behind them: no band, no status, no drift verdict. The band begins a sixth of the way across the card. It has to read as “your range wasn't established yet”, not as a clipping bug.",
    view: {
      restingToday: 59,
      recoveryScore: 79,
      hrvToday: 90.2,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: 56,
          recoveryScore: 59,
          hrv: 55.7,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-11",
          restingHr: 56,
          recoveryScore: 71,
          hrv: 101.2,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-12",
          restingHr: 56,
          recoveryScore: 74,
          hrv: 81.9,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-13",
          restingHr: 57,
          recoveryScore: 57,
          hrv: 88.4,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-14",
          restingHr: 60,
          recoveryScore: 68,
          hrv: 88.7,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-15",
          restingHr: 56,
          recoveryScore: 63,
          hrv: 70.9,
          baselineAvg: 79.3,
          balancedLow: 56.2,
          balancedHigh: 102.3,
          zScore: -0.36,
          status: "balanced",
        },
        {
          date: "2026-07-16",
          restingHr: 56,
          recoveryScore: 63,
          hrv: 98.5,
          baselineAvg: 78.7,
          balancedLow: 56.3,
          balancedHigh: 101.1,
          zScore: 0.88,
          status: "balanced",
        },
        {
          date: "2026-07-17",
          restingHr: 57,
          recoveryScore: 62,
          hrv: 68.9,
          baselineAvg: 79.9,
          balancedLow: 57.8,
          balancedHigh: 102.1,
          zScore: -0.5,
          status: "balanced",
        },
        {
          date: "2026-07-18",
          restingHr: 60,
          recoveryScore: 67,
          hrv: 101.5,
          baselineAvg: 79.3,
          balancedLow: 57.6,
          balancedHigh: 101,
          zScore: 1.02,
          status: "elevated",
        },
        {
          date: "2026-07-19",
          restingHr: 58,
          recoveryScore: 79,
          hrv: 59.4,
          baselineAvg: 80.5,
          balancedLow: 58.9,
          balancedHigh: 102.2,
          zScore: -0.97,
          status: "balanced",
        },
        {
          date: "2026-07-20",
          restingHr: 59,
          recoveryScore: 61,
          hrv: 101.7,
          baselineAvg: 79.4,
          balancedLow: 57.8,
          balancedHigh: 101,
          zScore: 1.03,
          status: "elevated",
        },
        {
          date: "2026-07-21",
          restingHr: 57,
          recoveryScore: 70,
          hrv: 97.1,
          baselineAvg: 80.5,
          balancedLow: 58.9,
          balancedHigh: 102.1,
          zScore: 0.77,
          status: "balanced",
        },
        {
          date: "2026-07-22",
          restingHr: 56,
          recoveryScore: 68,
          hrv: 83.2,
          baselineAvg: 81.3,
          balancedLow: 59.9,
          balancedHigh: 102.7,
          zScore: 0.09,
          status: "balanced",
        },
        {
          date: "2026-07-23",
          restingHr: 57,
          recoveryScore: 60,
          hrv: 57.8,
          baselineAvg: 81.4,
          balancedLow: 60.5,
          balancedHigh: 102.3,
          zScore: -1.13,
          status: "suppressed",
        },
        {
          date: "2026-07-24",
          restingHr: 57,
          recoveryScore: 67,
          hrv: 64,
          baselineAvg: 80.4,
          balancedLow: 59.4,
          balancedHigh: 101.4,
          zScore: -0.78,
          status: "balanced",
        },
        {
          date: "2026-07-25",
          restingHr: 57,
          recoveryScore: 77,
          hrv: 96.5,
          baselineAvg: 79.7,
          balancedLow: 58.9,
          balancedHigh: 100.5,
          zScore: 0.81,
          status: "balanced",
        },
        {
          date: "2026-07-26",
          restingHr: 57,
          recoveryScore: 75,
          hrv: 103.5,
          baselineAvg: 80.4,
          balancedLow: 59.7,
          balancedHigh: 101,
          zScore: 1.12,
          status: "elevated",
        },
        {
          date: "2026-07-27",
          restingHr: 57,
          recoveryScore: 67,
          hrv: 57.7,
          baselineAvg: 81.3,
          balancedLow: 60.5,
          balancedHigh: 102,
          zScore: -1.14,
          status: "suppressed",
        },
        {
          date: "2026-07-28",
          restingHr: 58,
          recoveryScore: 60,
          hrv: 88.9,
          baselineAvg: 80.4,
          balancedLow: 59.5,
          balancedHigh: 101.2,
          zScore: 0.41,
          status: "balanced",
        },
        {
          date: "2026-07-29",
          restingHr: 56,
          recoveryScore: 56,
          hrv: 88.2,
          baselineAvg: 80.7,
          balancedLow: 60.2,
          balancedHigh: 101.2,
          zScore: 0.37,
          status: "balanced",
        },
        {
          date: "2026-07-30",
          restingHr: 60,
          recoveryScore: 63,
          hrv: 78.8,
          baselineAvg: 80.9,
          balancedLow: 60.7,
          balancedHigh: 101.2,
          zScore: -0.11,
          status: "balanced",
        },
        {
          date: "2026-07-31",
          restingHr: 59,
          recoveryScore: 55,
          hrv: 78.1,
          baselineAvg: 80.9,
          balancedLow: 61,
          balancedHigh: 100.8,
          zScore: -0.14,
          status: "balanced",
        },
        {
          date: "2026-08-01",
          restingHr: 60,
          recoveryScore: 71,
          hrv: 85.5,
          baselineAvg: 82.3,
          balancedLow: 64.2,
          balancedHigh: 100.4,
          zScore: 0.18,
          status: "balanced",
        },
        {
          date: "2026-08-02",
          restingHr: 57,
          recoveryScore: 61,
          hrv: 112.2,
          baselineAvg: 81.5,
          balancedLow: 64,
          balancedHigh: 99,
          zScore: 1.76,
          status: "elevated",
        },
        {
          date: "2026-08-03",
          restingHr: 57,
          recoveryScore: 78,
          hrv: 110.2,
          baselineAvg: 83.3,
          balancedLow: 65.5,
          balancedHigh: 101.1,
          zScore: 1.51,
          status: "elevated",
        },
        {
          date: "2026-08-04",
          restingHr: 58,
          recoveryScore: 66,
          hrv: 110.9,
          baselineAvg: 85.3,
          balancedLow: 67.9,
          balancedHigh: 102.6,
          zScore: 1.48,
          status: "elevated",
        },
        {
          date: "2026-08-05",
          restingHr: 58,
          recoveryScore: 59,
          hrv: 78.6,
          baselineAvg: 87.1,
          balancedLow: 69.9,
          balancedHigh: 104.2,
          zScore: -0.49,
          status: "balanced",
        },
        {
          date: "2026-08-06",
          restingHr: 57,
          recoveryScore: 63,
          hrv: 101.4,
          baselineAvg: 86.6,
          balancedLow: 69.4,
          balancedHigh: 103.8,
          zScore: 0.86,
          status: "balanced",
        },
        {
          date: "2026-08-07",
          restingHr: 58,
          recoveryScore: 74,
          hrv: 71.2,
          baselineAvg: 86.1,
          balancedLow: 69.6,
          balancedHigh: 102.6,
          zScore: -0.9,
          status: "balanced",
        },
        {
          date: "2026-08-08",
          restingHr: 60,
          recoveryScore: 70,
          hrv: 39.5,
          baselineAvg: 85.8,
          balancedLow: 69.2,
          balancedHigh: 102.5,
          zScore: -2.79,
          status: "suppressed",
        },
        {
          date: "2026-08-09",
          restingHr: 59,
          recoveryScore: 79,
          hrv: 90.2,
          baselineAvg: 84,
          balancedLow: 65.5,
          balancedHigh: 102.5,
          zScore: 0.34,
          status: "balanced",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: 58.2,
        restingHrDays: 28,
        hrvAvg: 84,
        hrvStdDev: 18.5,
        hrvDays: 30,
        recoveryScoreAvg: 68.4,
        recoveryScoreDays: 28,
      },
      hrv: {
        status: "balanced",
        balancedLow: 65.5,
        balancedHigh: 102.5,
        zScore: 0.34,
        trend: "rising",
        shortAvg: 86,
      },
      baselineTrend: {
        direction: "unknown",
        deltaMs: null,
        fromAvg: null,
        overDays: 28,
      },
    },
  },
  calibrating: {
    label: "Calibrating",
    blurb:
      "Nine nights in. Every average, bound and z is null and both verdicts are unknown. No band anywhere, no chart frame drawn around nothing, no NaN. Every new Whoop user lives here for a fortnight.",
    view: {
      restingToday: 58,
      recoveryScore: 70,
      hrvToday: 77.4,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-11",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-12",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-13",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-14",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-15",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-16",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-17",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-18",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-19",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-20",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-21",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-22",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-23",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-24",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-25",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-26",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-27",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-28",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-29",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-30",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-31",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-01",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-02",
          restingHr: 59,
          recoveryScore: 76,
          hrv: 126.4,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-03",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 93.5,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-04",
          restingHr: 56,
          recoveryScore: 79,
          hrv: 66.4,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-05",
          restingHr: 57,
          recoveryScore: 62,
          hrv: 102,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-06",
          restingHr: 58,
          recoveryScore: 71,
          hrv: 86,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-07",
          restingHr: 58,
          recoveryScore: 78,
          hrv: 66.1,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-08",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 103.1,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-09",
          restingHr: 58,
          recoveryScore: 70,
          hrv: 77.4,
          baselineAvg: null,
          balancedLow: null,
          balancedHigh: null,
          zScore: null,
          status: "unknown",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: null,
        restingHrDays: 9,
        hrvAvg: null,
        hrvStdDev: null,
        hrvDays: 9,
        recoveryScoreAvg: null,
        recoveryScoreDays: 9,
      },
      hrv: {
        status: "unknown",
        balancedLow: null,
        balancedHigh: null,
        zScore: null,
        trend: "unknown",
        shortAvg: null,
      },
      baselineTrend: {
        direction: "unknown",
        deltaMs: null,
        fromAvg: null,
        overDays: 28,
      },
    },
  },
  "no-reading-yet": {
    label: "No reading yet",
    blurb:
      "7am, before the webhook lands. Today's mark is absent — but the 30 prior nights, the band and the 6 ms climb are all still true and still printable. A variant that degrades to em-dashes here has failed the brief.",
    view: {
      restingToday: null,
      recoveryScore: null,
      hrvToday: null,
      spark: [58, 59, 57, 59],
      days: [
        {
          date: "2026-07-10",
          restingHr: 59,
          recoveryScore: 79,
          hrv: 100.2,
          baselineAvg: 79.9,
          balancedLow: 59.5,
          balancedHigh: 100.2,
          zScore: 1,
          status: "balanced",
        },
        {
          date: "2026-07-11",
          restingHr: 59,
          recoveryScore: 68,
          hrv: 80.1,
          baselineAvg: 81.5,
          balancedLow: 61.4,
          balancedHigh: 101.5,
          zScore: -0.07,
          status: "balanced",
        },
        {
          date: "2026-07-12",
          restingHr: 57,
          recoveryScore: 60,
          hrv: 72.2,
          baselineAvg: 81.8,
          balancedLow: 61.8,
          balancedHigh: 101.8,
          zScore: -0.48,
          status: "balanced",
        },
        {
          date: "2026-07-13",
          restingHr: 57,
          recoveryScore: 76,
          hrv: 96.7,
          baselineAvg: 81.1,
          balancedLow: 61.2,
          balancedHigh: 101.1,
          zScore: 0.78,
          status: "balanced",
        },
        {
          date: "2026-07-14",
          restingHr: 59,
          recoveryScore: 60,
          hrv: 73,
          baselineAvg: 81.6,
          balancedLow: 61.4,
          balancedHigh: 101.7,
          zScore: -0.42,
          status: "balanced",
        },
        {
          date: "2026-07-15",
          restingHr: 55,
          recoveryScore: 66,
          hrv: 93,
          baselineAvg: 81.5,
          balancedLow: 61.3,
          balancedHigh: 101.6,
          zScore: 0.57,
          status: "balanced",
        },
        {
          date: "2026-07-16",
          restingHr: 59,
          recoveryScore: 69,
          hrv: 79.8,
          baselineAvg: 83.4,
          balancedLow: 64.8,
          balancedHigh: 101.9,
          zScore: -0.19,
          status: "balanced",
        },
        {
          date: "2026-07-17",
          restingHr: 56,
          recoveryScore: 64,
          hrv: 63.2,
          baselineAvg: 83.3,
          balancedLow: 64.8,
          balancedHigh: 101.9,
          zScore: -1.09,
          status: "suppressed",
        },
        {
          date: "2026-07-18",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 81.8,
          balancedLow: 63.5,
          balancedHigh: 100.2,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-07-19",
          restingHr: 59,
          recoveryScore: 65,
          hrv: 70,
          baselineAvg: 82.9,
          balancedLow: 65.2,
          balancedHigh: 100.6,
          zScore: -0.73,
          status: "balanced",
        },
        {
          date: "2026-07-20",
          restingHr: 55,
          recoveryScore: 80,
          hrv: 89.5,
          baselineAvg: 82.2,
          balancedLow: 64.4,
          balancedHigh: 100,
          zScore: 0.41,
          status: "balanced",
        },
        {
          date: "2026-07-21",
          restingHr: 59,
          recoveryScore: 63,
          hrv: 74.1,
          baselineAvg: 83.8,
          balancedLow: 67.6,
          balancedHigh: 100,
          zScore: -0.6,
          status: "balanced",
        },
        {
          date: "2026-07-22",
          restingHr: 58,
          recoveryScore: 64,
          hrv: 75.2,
          baselineAvg: 83.6,
          balancedLow: 67.3,
          balancedHigh: 99.9,
          zScore: -0.51,
          status: "balanced",
        },
        {
          date: "2026-07-23",
          restingHr: 58,
          recoveryScore: 76,
          hrv: 144.7,
          baselineAvg: 83.3,
          balancedLow: 67.2,
          balancedHigh: 99.4,
          zScore: 3.82,
          status: "elevated",
        },
        {
          date: "2026-07-24",
          restingHr: 59,
          recoveryScore: 62,
          hrv: 100.1,
          baselineAvg: 84.4,
          balancedLow: 65.5,
          balancedHigh: 103.2,
          zScore: 0.84,
          status: "balanced",
        },
        {
          date: "2026-07-25",
          restingHr: 58,
          recoveryScore: 67,
          hrv: 120.9,
          baselineAvg: 85.7,
          balancedLow: 67.1,
          balancedHigh: 104.2,
          zScore: 1.9,
          status: "elevated",
        },
        {
          date: "2026-07-26",
          restingHr: 55,
          recoveryScore: 78,
          hrv: 106.4,
          baselineAvg: 87.2,
          balancedLow: 67.6,
          balancedHigh: 106.8,
          zScore: 0.98,
          status: "balanced",
        },
        {
          date: "2026-07-27",
          restingHr: 57,
          recoveryScore: 79,
          hrv: 55.3,
          baselineAvg: 87.8,
          balancedLow: 68,
          balancedHigh: 107.7,
          zScore: -1.64,
          status: "suppressed",
        },
        {
          date: "2026-07-28",
          restingHr: 55,
          recoveryScore: 72,
          hrv: 86.5,
          baselineAvg: 87.4,
          balancedLow: 66.9,
          balancedHigh: 107.8,
          zScore: -0.04,
          status: "balanced",
        },
        {
          date: "2026-07-29",
          restingHr: 57,
          recoveryScore: 72,
          hrv: 72.9,
          baselineAvg: 87.1,
          balancedLow: 66.7,
          balancedHigh: 107.6,
          zScore: -0.7,
          status: "balanced",
        },
        {
          date: "2026-07-30",
          restingHr: 59,
          recoveryScore: 67,
          hrv: 76.1,
          baselineAvg: 87.1,
          balancedLow: 66.6,
          balancedHigh: 107.5,
          zScore: -0.54,
          status: "balanced",
        },
        {
          date: "2026-07-31",
          restingHr: 57,
          recoveryScore: 80,
          hrv: 96.2,
          baselineAvg: 86.1,
          balancedLow: 65.8,
          balancedHigh: 106.5,
          zScore: 0.49,
          status: "balanced",
        },
        {
          date: "2026-08-01",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 87,
          balancedLow: 66.9,
          balancedHigh: 107.2,
          zScore: null,
          status: "unknown",
        },
        {
          date: "2026-08-02",
          restingHr: 59,
          recoveryScore: 76,
          hrv: 126.4,
          baselineAvg: 85.6,
          balancedLow: 66.6,
          balancedHigh: 104.7,
          zScore: 2.14,
          status: "elevated",
        },
        {
          date: "2026-08-03",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 93.5,
          baselineAvg: 87.3,
          balancedLow: 66.8,
          balancedHigh: 107.7,
          zScore: 0.3,
          status: "balanced",
        },
        {
          date: "2026-08-04",
          restingHr: 56,
          recoveryScore: 79,
          hrv: 66.4,
          baselineAvg: 88.8,
          balancedLow: 69.5,
          balancedHigh: 108.1,
          zScore: -1.16,
          status: "suppressed",
        },
        {
          date: "2026-08-05",
          restingHr: 57,
          recoveryScore: 62,
          hrv: 102,
          baselineAvg: 88.1,
          balancedLow: 68.3,
          balancedHigh: 107.8,
          zScore: 0.71,
          status: "balanced",
        },
        {
          date: "2026-08-06",
          restingHr: 58,
          recoveryScore: 71,
          hrv: 86,
          baselineAvg: 88.4,
          balancedLow: 68.5,
          balancedHigh: 108.3,
          zScore: -0.12,
          status: "balanced",
        },
        {
          date: "2026-08-07",
          restingHr: 58,
          recoveryScore: 78,
          hrv: 66.1,
          baselineAvg: 88,
          balancedLow: 68.2,
          balancedHigh: 107.8,
          zScore: -1.11,
          status: "suppressed",
        },
        {
          date: "2026-08-08",
          restingHr: 57,
          recoveryScore: 58,
          hrv: 103.1,
          baselineAvg: 87,
          balancedLow: 66.8,
          balancedHigh: 107.2,
          zScore: 0.8,
          status: "balanced",
        },
        {
          date: "2026-08-09",
          restingHr: null,
          recoveryScore: null,
          hrv: null,
          baselineAvg: 88.2,
          balancedLow: 68.1,
          balancedHigh: 108.3,
          zScore: null,
          status: "unknown",
        },
      ],
      baseline: {
        windowDays: 30,
        restingHrAvg: 57.2,
        restingHrDays: 28,
        hrvAvg: 88.2,
        hrvStdDev: 20.1,
        hrvDays: 30,
        recoveryScoreAvg: 70.4,
        recoveryScoreDays: 28,
      },
      hrv: {
        status: "unknown",
        balancedLow: 68.1,
        balancedHigh: 108.3,
        zScore: null,
        trend: "steady",
        shortAvg: 86.2,
      },
      baselineTrend: {
        direction: "rising",
        deltaMs: 6.4,
        fromAvg: 81.8,
        overDays: 28,
      },
    },
  },
};
