/// <reference types="vitest/globals" />

import type { RecoveryDayPoint, RecoveryView } from "@/lib/dashboard";
import { ROLLING_WINDOW_NIGHTS } from "@/app/(app)/dashboard/_components/recovery/hrv-chart";
import {
  calibratingView,
  defaultView,
  FIXTURE_TODAY,
  recordedMornings,
  sparseYearView,
} from "../fixtures";
import {
  addDays,
  bandCounts,
  columnWidth,
  isMissingNight,
  LEAD_IN,
  ledgerRows,
  longDate,
  mean,
  monthLabel,
  pageCount,
  pageOf,
  parseISO,
  PLOT_INSET,
  prepareDeck,
  shortDate,
  tail,
  toISO,
  WINDOWS,
  xAt,
} from "./shared";

/** A morning with everything present; override only what a test is about. */
function day(over: Partial<RecoveryDayPoint> = {}): RecoveryDayPoint {
  return {
    date: "2026-08-12",
    restingHr: 52,
    recoveryScore: 71,
    hrv: 88,
    baselineAvg: 88,
    balancedLow: 76,
    balancedHigh: 100,
    zScore: 0,
    status: "balanced",
    ...over,
  };
}

const daysOf = (view: RecoveryView): RecoveryDayPoint[] => view.days ?? [];
const last = <T>(rows: T[]): T => rows[rows.length - 1];

describe("dates — local parts, never `new Date(iso)`", () => {
  test("longDate and shortDate do not shift across a timezone boundary", () => {
    // Split into Y/M/D and handed to the local Date constructor, these read the
    // same in every zone. `new Date("2026-08-12")` is UTC midnight, which is the
    // 11th for every user west of Greenwich — the bug this avoids.
    expect(longDate("2026-08-12")).toBe("Wed 12 Aug");
    expect(shortDate("2026-08-12")).toBe("12 Aug");
    expect(longDate("2026-01-01")).toBe("Thu 1 Jan");
    expect(shortDate("2026-01-01")).toBe("1 Jan");
    expect(longDate("2025-12-31")).toBe("Wed 31 Dec");
    expect(monthLabel("2026-03-05")).toBe("Mar");
  });

  test("addDays rolls over months, years and a leap day, and round-trips through toISO", () => {
    // The fixture's entire 428-day axis is generated by `addDays`, so an
    // off-by-one or a UTC round-trip here would move every date on the page.
    expect(addDays("2026-08-12", 1)).toBe("2026-08-13");
    expect(addDays("2026-08-12", -1)).toBe("2026-08-11");
    expect(addDays("2026-08-12", 0)).toBe("2026-08-12");
    expect(addDays("2026-08-31", 1)).toBe("2026-09-01");
    expect(addDays("2026-01-01", -1)).toBe("2025-12-31");
    expect(addDays("2024-02-28", 1)).toBe("2024-02-29");
    expect(addDays("2026-02-28", 1)).toBe("2026-03-01");
    // 428 back from the fixture's today is the fixture's first morning.
    expect(addDays("2026-08-12", -427)).toBe("2025-06-11");
    expect(toISO(parseISO("2025-06-11"))).toBe("2025-06-11");
  });

  test("the fixture's own dates print the weekdays the fixture claims", () => {
    expect(longDate(FIXTURE_TODAY)).toBe("Wed 12 Aug");
    expect(longDate("2026-08-07")).toBe("Fri 7 Aug");
  });
});

describe("ledgerRows — the charts keep the slot, the record has nothing to record", () => {
  const threeMornings = [
    day({ date: "2026-08-10", recoveryScore: 52 }),
    day({ date: "2026-08-11", recoveryScore: null, restingHr: null, hrv: null }),
    day({ date: "2026-08-12", recoveryScore: null, restingHr: 69, hrv: 45 }),
  ];

  test("a wholly-missing morning is dropped and a partial-null one is kept", () => {
    expect(ledgerRows(threeMornings).map((d) => d.date)).toEqual(["2026-08-12", "2026-08-10"]);
    expect(isMissingNight(threeMornings[1])).toBe(true);
    expect(isMissingNight(threeMornings[2])).toBe(false);
  });

  test("rows are newest first", () => {
    const rows = ledgerRows(daysOf(defaultView()));
    expect(rows[0].date).toBe(FIXTURE_TODAY);
    expect(rows[1].date).toBe("2026-08-11");
    expect(last(rows).date < rows[0].date).toBe(true);
  });

  test("ledgerRows does not mutate the series it was handed", () => {
    const days = [...threeMornings];
    ledgerRows(days);
    expect(days.map((d) => d.date)).toEqual(["2026-08-10", "2026-08-11", "2026-08-12"]);
  });
});

describe("paging — the bodyweight readings table's twenty to a page", () => {
  const rows = Array.from({ length: 425 }, (_, i) => i);

  test("425 rows page to 22, and page 22 holds the remainder", () => {
    expect(pageCount(rows.length)).toBe(22);
    expect(pageOf(rows, 1)).toHaveLength(20);
    expect(pageOf(rows, 1)[0]).toBe(0);
    expect(pageOf(rows, 22)).toEqual([420, 421, 422, 423, 424]);
    expect(pageOf(rows, 23)).toEqual([]);
  });

  test("an empty ledger is still one page, never zero", () => {
    expect(pageCount(0)).toBe(1);
    expect(pageCount(20)).toBe(1);
    expect(pageCount(21)).toBe(2);
  });
});

describe("bandCounts — Whoop's thirds, delegated to recoveryBand", () => {
  test("the cut points are the tiles' own, and a scoreless morning counts nowhere", () => {
    const counts = bandCounts([
      day({ recoveryScore: 67 }),
      day({ recoveryScore: 100 }),
      day({ recoveryScore: 66 }),
      day({ recoveryScore: 34 }),
      day({ recoveryScore: 33 }),
      day({ recoveryScore: 0 }),
      day({ recoveryScore: null }),
    ]);
    expect(counts).toEqual({ green: 2, yellow: 2, red: 2 });
  });

  test("the 30-day window's mix matches the fixture, and accounts for every scored morning", () => {
    const { days } = prepareDeck(defaultView(), 30);
    const counts = bandCounts(days);
    expect(counts).toEqual({ green: 13, yellow: 10, red: 5 });
    // 30 slots, one of them Friday's absence and one Sunday's missing score.
    expect(counts.green + counts.yellow + counts.red).toBe(
      days.filter((d) => d.recoveryScore !== null).length,
    );
    expect(days).toHaveLength(30);
  });
});

describe("xAt — the one x-mapping the three rows and the crosshair share", () => {
  test("the ends land exactly on the plot inset, so the crosshair can too", () => {
    expect(xAt(0, 30, 300)).toBe(PLOT_INSET);
    // Right-hand end to float tolerance: `4.6` is not representable, so the
    // last column lands a 1e-13 of a pixel wide of `width - PLOT_INSET`.
    expect(xAt(29, 30, 300)).toBeCloseTo(300 - PLOT_INSET, 9);
  });

  test("a single morning takes the centre of the drawable box", () => {
    expect(xAt(0, 1, 300)).toBe(150);
  });

  test("the inset is the HRV chart's own largest mark radius", () => {
    expect(PLOT_INSET).toBe(4.6);
  });

  test("a column is the step between two adjacent centres, less a pixel of air", () => {
    // The score row and the resting-HR row take this same figure, which is the
    // point of it living beside `xAt` rather than twice in the two plots.
    expect(columnWidth(30, 300)).toBeCloseTo(xAt(1, 30, 300) - xAt(0, 30, 300) - 1, 9);
  });

  test("a 365-morning year still renders a column, never a zero-width one", () => {
    // At the 1y window the step is well under a pixel; without the floor the
    // whole year would draw as nothing at all.
    expect(xAt(1, 365, 260) - xAt(0, 365, 260)).toBeLessThan(1);
    expect(columnWidth(365, 260)).toBe(1);
  });

  test("a single morning's column is the drawable box it is centred in", () => {
    expect(columnWidth(1, 300)).toBeCloseTo(300 - 2 * PLOT_INSET - 1, 9);
  });
});

describe("mean — the one figure the server never emits", () => {
  test("averages the present values and returns null when there are none", () => {
    expect(mean([50, 52, 54])).toBe(52);
    expect(mean([50, null, 54])).toBe(52);
    expect(mean([null, null])).toBeNull();
    expect(mean([])).toBeNull();
  });
});

describe("prepareDeck — the correction-1 contract", () => {
  test("LEAD_IN is the rolling window minus one, never the literal 6", () => {
    expect(LEAD_IN).toBe(ROLLING_WINDOW_NIGHTS - 1);
  });

  for (const win of WINDOWS) {
    test(`${win.key}: the HRV series and the deck's days are one list`, () => {
      const { chart, days } = prepareDeck(defaultView(), win.days);
      expect(chart).not.toBeNull();
      // Not "equal lengths" by luck — the SAME objects, so the score and
      // resting-HR rows cannot drift from the curve above them.
      expect(days).toBe(chart!.series);
      expect(chart!.series).toHaveLength(days.length);
      expect(days).toHaveLength(win.days);
      expect(days[0].date).toBe(chart!.series[0].date);
      expect(last(days).date).toBe(last(chart!.series).date);
      // Every window is a tail ending on the last stored morning — the HRV
      // panel's first invariant depends on it.
      expect(last(days).date).toBe(FIXTURE_TODAY);
    });
  }

  test("the lead-in is what makes the axis true — trimming it shortens the series", () => {
    const view = defaultView();
    const withLeadIn = { ...view, days: tail(daysOf(view), 30 + LEAD_IN) };
    expect(prepareDeck(withLeadIn, 30).days).toHaveLength(30);

    // The regression this pins: hand the chart the window alone and it draws
    // LEAD_IN mornings fewer than the columns beside it, which is the six-day
    // skew correction 1 exists to remove.
    const trimmed = { ...view, days: tail(daysOf(view), 30) };
    expect(prepareDeck(trimmed, 30).days).toHaveLength(30 - LEAD_IN);
  });

  test("history shorter than window + LEAD_IN narrows all three rows to one contiguous tail", () => {
    const view = defaultView();
    const short = { ...view, days: tail(daysOf(view), 40) };
    const { chart, days } = prepareDeck(short, 90);

    expect(chart).not.toBeNull();
    expect(days).toBe(chart!.series);
    expect(days).toHaveLength(40 - LEAD_IN);
    // Contiguous, and still the tail: same objects, same order, ending today.
    expect(days).toEqual(tail(daysOf(short), days.length));
    expect(last(days).date).toBe(FIXTURE_TODAY);
  });

  test("a sparse year narrows the deck to what the chart could actually draw", () => {
    const sparse = sparseYearView();
    const { chart, days } = prepareDeck(sparse, 365);

    expect(daysOf(sparse)).toHaveLength(365);
    expect(chart).not.toBeNull();
    expect(days).toBe(chart!.series);
    expect(days.length).toBeLessThan(365);
    expect(days).toEqual(tail(daysOf(sparse), days.length));
  });

  test("a calibrating view yields no chart, and the other two rows span the window", () => {
    const calibrating = calibratingView();
    const { chart, days } = prepareDeck(calibrating, 30);

    expect(chart).toBeNull();
    // Nine mornings is all the history there is, so the requested 30 narrows to
    // it — the score and resting-HR rows still draw, because Whoop's bands need
    // no baseline.
    expect(days).toEqual(tail(daysOf(calibrating), 30));
    expect(days).toHaveLength(9);
  });

  test("a long history with no baseline yet still spans the full requested window", () => {
    const view = defaultView();
    // The server withholds `hrvAvg` until the baseline calibrates; the guard in
    // `prepareHrvChart` reads it, so this is the calibrating state on a payload
    // that is otherwise deep.
    const uncalibrated: RecoveryView = {
      ...view,
      baseline: { ...view.baseline!, hrvAvg: null },
    };
    const { chart, days } = prepareDeck(uncalibrated, 30);

    expect(chart).toBeNull();
    expect(days).toHaveLength(30);
    expect(last(days).date).toBe(FIXTURE_TODAY);
  });

  test("a view with no days at all yields no chart and no columns", () => {
    const { chart, days } = prepareDeck({ restingToday: null, recoveryScore: null, spark: [] }, 30);
    expect(chart).toBeNull();
    expect(days).toEqual([]);
  });
});

/**
 * The fixture's headline claims, pinned here rather than in a `fixtures.test.ts`
 * of their own. Every other test on this page — the ledger's paging, the band
 * mix, the deck's alignment — takes these as its premise, so an edit to the
 * generator that quietly moves one must fail HERE rather than turn a dozen
 * assertions elsewhere into statements about a different athlete.
 */
describe("the fixture is contract", () => {
  const view = defaultView();
  const days = daysOf(view);
  const on = (date: string) => days.find((d) => d.date === date);

  test("428 mornings of history, ending on Wed 12 Aug 2026", () => {
    expect(days).toHaveLength(428);
    expect(last(days).date).toBe(FIXTURE_TODAY);
    expect(days[0].date).toBe("2025-06-11");
    // Deep enough that the ledger really pages, which is the point of 428.
    expect(pageCount(ledgerRows(days).length)).toBeGreaterThan(20);
    expect(recordedMornings(view)).toBe(416);
  });

  test("today is the bad morning the page must stay legible on: 13 · 69 bpm · 45 ms", () => {
    expect(on(FIXTURE_TODAY)).toMatchObject({ recoveryScore: 13, restingHr: 69, hrv: 45 });
    expect(on("2026-08-11")).toMatchObject({ recoveryScore: 78, restingHr: 50, hrv: 106 });
    expect(on("2026-08-10")).toMatchObject({ recoveryScore: 52, restingHr: 47, hrv: 96 });
  });

  test("Sunday 9 Aug is scoreless but recorded — a partial-null morning, not an absence", () => {
    expect(on("2026-08-09")).toMatchObject({ recoveryScore: null, restingHr: 51, hrv: 88 });
    expect(isMissingNight(on("2026-08-09")!)).toBe(false);
    expect(ledgerRows(days).map((d) => d.date)).toContain("2026-08-09");
  });

  test("Friday 7 Aug has no row at all — a slot on the axis, nothing in the ledger", () => {
    expect(isMissingNight(on("2026-08-07")!)).toBe(true);
    expect(ledgerRows(days).map((d) => d.date)).not.toContain("2026-08-07");
    // The slot survives, so the axis does not compress over the absence.
    expect(prepareDeck(view, 30).days.map((d) => d.date)).toContain("2026-08-07");
  });

  test("five consecutive below-band HRV nights from 21 Jul — five, and bounded", () => {
    const suppressed = days.filter((d) => d.status === "suppressed" && d.date >= "2026-07-01");
    const run = suppressed.filter((d) => d.date >= "2026-07-21" && d.date <= "2026-07-25");
    expect(run).toHaveLength(5);
    expect(run.map((d) => d.date)).toEqual([
      "2026-07-21",
      "2026-07-22",
      "2026-07-23",
      "2026-07-24",
      "2026-07-25",
    ]);
    // The run is a RUN: the mornings either side of it are not suppressed, so a
    // test counting a sustained dip counts five and not six.
    expect(on("2026-07-20")!.status).not.toBe("suppressed");
    expect(on("2026-07-26")!.status).not.toBe("suppressed");
  });

  test("the sparse year is a full year of slots with only a month recorded", () => {
    const sparse = sparseYearView();
    expect(daysOf(sparse)).toHaveLength(365);
    expect(recordedMornings(sparse)).toBeLessThan(40);
    expect(last(daysOf(sparse)).date).toBe(FIXTURE_TODAY);
  });

  test("the calibrating view is nine mornings with no baseline to speak of", () => {
    const calibrating = calibratingView();
    expect(daysOf(calibrating)).toHaveLength(9);
    expect(calibrating.baseline?.hrvAvg).toBeNull();
    expect(calibrating.hrv?.shortAvg).not.toBeNull();
  });
});
